name: Deploy to GitHub Pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
       # uses GitHub's checkout action to checkout code form the master branch
      - uses: actions/checkout@v2
      # sets up .NET Core SDK 3.1
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
      # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish Pentaforce.Beta.Wiki/Pentaforce.Beta.Wiki.csproj -c Release -o release --nologo
      # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to Pentaforce
        run: sed -i 's/<base href="\/" \/>/<base href="https:\/\/mcrev4.github.io\/Pentaforce\/" \/>/g' release/wwwroot/index.html
      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      - name: Deploy to GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: JamesIves/github-pages-deploy-action@13046b614c663b56cba4dda3f30b9736a748b80d
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: pages
          FOLDER: release/wwwroot
